services:
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - 8899:8080
    environment:
      KAFKA_BROKERS: kafka:29092
    container_name: kafka-console
    networks:
      - czt-network

  zookeeper:
    platform: linux/arm64/v8
    image: docker.io/bitnami/zookeeper:3
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - czt-network

  kafka:
    platform: linux/arm64/v8
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper
    networks:
      - czt-network

networks:
  czt-network:
    driver: bridge
