spring.application.name: demo

kafka-mvc:
  bootstrap-servers: localhost:9092
  consumer:
    name: "service-a-consumer"
    threads:
      max: 50
      start: 10
  producer:
    replyTopic: "service.a.response"
    timeout: 10000