spring.application.name: demo
server.port: 8002
kafka-mvc:
  bootstrap-servers: 192.168.1.19:9092
  consumer:
    name: "service-a-consumer"
    threads:
      max: 50
      start: 10
  producer:
    replyTopic: "service.a.response"
    timeout: 10000

